# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9ae758f4df81b7f9de5b21529754a6ca6c5c01fe2521b9dfdfd3832f1c865b9d48bbf8b46ed84b42c2f2704087fae159f05b557009fc4a1c5243fc84aea1afe

test:
  secret_key_base: e40c28682ec416b5c0ece9fd8c35d5531c4d08a02dd26c007db2e34e5b7422a8b54717c4d510e09a716df01b682b9d3146290005b941e00c1e75301f58bd3101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
